const mysql = require('mysql');

var connection = mysql.createConnection({
   host: '127.0.0.1',
   user: 'root',
   password: '',
   database: 'crm'
});

const namesArray = ['Ihsan Norton', 'Belinda Simon', 'Adyan Dyer', 'Kasey Ibarra', 'Mairead Allen', 'Ahsan Whyte', 'Moshe Berg', 'Fabio Rasmussen', 'Meghan Leech', 'Levison Peralta', 'Aadil Mckinney', 'Ava-Rose Joyce', 'Asa Nielsen', 'Jessica Britt', 'Tristan Deleon', 'Penelope Bains', 'Haya Lopez', 'Fraser Coffey', 'Melisa Ramirez', 'Kalvin Alvarez', 'Edna Collier', 'Zeshan Beck', 'Amber-Rose Church', 'Willie Page', 'Barbara Frazier', 'Prisha Dickens', 'Amisha Poole', 'Annabell Booker', 'Tayyab Crossley', 'Ada Drew', 'Presley Hutchinson', 'Shayne Broadhurst', 'Sharna Benton', 'Ace Rodriguez', 'Samad Meyer', 'Tasnim Plummer', 'Gideon Munro', 'Havin Madden', 'Cobie Snyder', 'Nichole Singleton', 'Abdirahman Mendez', 'Rudy Milne', 'Jaye Greene', 'Theo Chaney', 'Mia-Rose Ewing', 'Rogan Singh', 'Jo Neal', 'Carmel Forrest', 'Varun Carey', 'Conner Howells', 'Rose Barr', 'Tayyib Fritz', 'Loretta Mullins', 'Lois Cleveland', 'Marian Turnbull', 'Mira Peck', 'Dione Firth', 'Etta Everett', 'Arman Robbins', 'Perry Black', 'Cayson Lim', 'Anne Bernard', 'Billy Wagner', 'Chandler Little', 'Layton Irvine', 'Fatema Wolfe', 'Can Seymour', 'Abi Peacock', 'Mylee Newman', 'Riaan Howard', 'Marcelina Hollis', 'Kristopher Marsden', 'Rajveer Tillman', 'Sullivan Finley', 'Brenna Leal', 'Corben Montoya', 'Bertram Herbert', 'Alina Perry', 'Kiara Webster', 'Frankie Graham', 'Fatima Mason', 'Lincoln Barrett', 'Gurpreet Waters', 'Marcia Wilcox', 'Amrita Mcclure', 'Neo Blackwell', 'Markus Forbes', 'Bill Bartlett', 'Roan Ventura', 'Aleeza Richardson', 'Allison Burke', 'Beatriz Parker', 'Elliott Person', 'Deon Williamson', 'Arya Norman', 'Franklyn Hurst', 'Mac Stafford', 'Shantelle Dawe', 'Lorelai Fitzpatrick', 'Kaitlin Payne'];
const titles = ['Accountant',
   'Auditor',
   'Actor',
   'Actuary',
   'Adhesive Bonding Machine Operator',
   'Tender',
   'Administrative Law Judge',
   'Administrative Services Manager',
   'Adult Basic and Secondary Education and Literacy Teacher',
   'Instructor',
   'Advertising Sales Agent',
   'Advertising and Promotions Manager',
   'Aerospace Engineering and Operations Technician',
   'Aerospace Engineer',
   'Agent',
   'Business Managers of Artist',
   'Agricultural Engineer',
   'Agricultural Equipment Operator',
   'Agricultural Inspector',
   'Agricultural Sciences Teacher',
   'Agricultural Worker',
   'Agricultural and Food Science Technician',
   'Air Traffic Controller',
   'Aircraft Cargo Handling Supervisor',
   'Aircraft Mechanic',
   'Service Technician',
   'Aircraft Structure',
   'Airfield Operations Specialist',
   'Airline Pilot',
   'All Occupation',
   'Ambulance Driver',
   'Attendant',
   'Amusement and Recreation Attendant',
   'Anesthesiologist',
   'Animal Breeder',
   'Animal Control Worker',
   'Animal Scientist',
   'Animal Trainer',
   'Anthropologist',
   'Archeologist',
   'Anthropology and Archeology Teacher',
   'Appraiser',
   'Assessors of Real Estate',
   'Arbitrator',
   'Architect',
   'Architectural and Civil Drafter',
   'Architectural and Engineering Manager',
   'Architecture Teacher',
   'Architecture and Engineering Occupation',
   'Archivist',
   'Area',
   'Art Director',
   'Artist',
   'Assembler',
   'Fabricator',
   'Astronomer',
   'Athlete',
   'Sports Competitor',
   'Athletic Trainer',
   'Atmospheric and Space Scientist',
   'Atmospheric',
   'Audio and Video Equipment Technician',
   'Audio-Visual and Multimedia Collections Specialist',
   'Audiologist',
   'Automotive Body and Related Repairer',
   'Automotive Glass Installer',
   'Repairer',
   'Automotive Service Technician',
   'Mechanic',
   'Automotive and Watercraft Service Attendant',
   'Avionics Technicians',
   'Baggage Porter',
   'Bellhop',
   'Bailiff',
   'Baker',
   'Barber',
   'Bartender',
   'Bicycle Repairer',
   'Bill and Account Collector',
   'Billing and Posting Clerk',
   'Biochemist',
   'Biophysicist',
   'Biological Science Teacher',
   'Biological Scientist',
   'Biological Technician',
   'Biomedical Engineer',
   'Boilermaker',
   'Bookkeeping',
   'Brickmason',
   'Blockmason',
   'Bridge and Lock Tender',
   'Broadcast News Analyst',
   'Broadcast Technician',
   'Brokerage Clerk',
   'Budget Analyst',
   'Building Cleaning Worker',
   'Bus Driver',
   'Bus Driver',
   'Bu',
   'Truck Mechanic',
   'Diesel Engine Specialist',
   'Business Operations Specialist',
   'Business Teacher',
   'Busines',
   'Financial Operations Occupation',
   'Butcher',
   'Meat Cutter',
   'Buyer',
   'Purchasing Agent',
   'Cabinetmaker',
   'Bench Carpenter',
   'Camera Operator',
   'Camera and Photographic Equipment Repairer',
   'Captain',
   'Cardiovascular Technologist',
   'Technician',
   'Career/Technical Education Teacher',
   'Career/Technical Education Teacher',
   'Cargo and Freight Agent',
   'Carpenter',
   'Carpet Installer',
   'Cartographer'];
const admins = [2, 6, 7, 9, 19];
const moblieVendor = ['050', '052', '054', '058'];
const phoneVendor = ['02', '03', '04', '08', '09'];
const emailVendors = ['gmail.com', 'yahoo.com', 'outlook.com', 'walla.com', 'icloud.com'];
const streets = ['5th Street North',
   '4th Avenue',
   'Summit Street',
   'Sherwood Drive',
   'Route 6',
   'Route 32',
   'Riverside Drive',
   'Railroad Avenue',
   'Primrose Lane',
   'Penn Street',
   'Park Drive',
   'Laurel Street',
   'Hillcrest Drive',
   'George Street',
   'Clinton Street',
   'Beech Street',
   '7th Avenue',
   '5th Street West',
   'Poplar Street',
   'Lafayette Avenue',
   'King Street',
   'Holly Drive',
   'Hillside Drive',
   'Heather Lane',
   'Grant Street',
   'Durham Road',
   'Cedar Lane',
   'Buckingham Drive',
   '6th Avenue',
   '4th Street North',
   'Wood Street',
   'Williams Street',
   'Warren Street',
   'Walnut Avenue',
   'Surrey Lane',
   'Route 29',
   'Route 10',
   'Ridge Avenue',
   'Mulberry Street',
   'Linden Street',
   'James Street',
   'Front Street North',
   'Franklin Avenue',
   'Elm Avenue',
   'College Avenue',
   'Clark Street',
   'Circle Drive',
   'Berkshire Drive',
   '6th Street North',
   'Woodland Avenue',
   'William Street',
   'Smith Street',
   'Shady Lane',
   'Oxford Court',
   'Myrtle Avenue',
   'Maple Lane',
   'Lafayette Street',
   'John Street',
   'Hilltop Road',
   'Highland Drive',
   'Hamilton Street',
   'Fulton Street',
   'Euclid Avenue',
   'Essex Court',
   'Creek Road',
   'Canal Street',
   'Cambridge Drive',
   'Cambridge Court',
   'Arch Street',
   '7th Street East',
   '2nd Street East',
   'York Road',
   'Windsor Court',
   'Magnolia Drive',
   'Linden Avenue',
   'Bartender',
   'Bicycle Repairer',
   'Bill and Account Collector',
   'Billing and Posting Clerk',
   'Biochemist',
   'Biophysicist',
   'Biological Science Teacher',
   'Biological Scientist',
   'Biological Technician',
   'Biomedical Engineer',
   'Boilermaker',
   'Bookkeeping',
   'Brickmason',
   'Blockmason',
   'Bridge and Lock Tender',
   'Broadcast News Analyst',
   'Broadcast Technician',
   'Brokerage Clerk',
   'Budget Analyst',
   'Building Cleaning Worker',
   'Bus Driver',
   'Bus Driver',
   'Bu',
   'Truck Mechanic',
   'Diesel Engine Specialist',
   'Business Operations Specialist',
   'Business Teacher',
   'Busines',
   'Financial Operations Occupation',
   'Butcher',
   'Meat Cutter',
   'Buyer',
   'Purchasing Agent',
   'Cabinetmaker',
   'Bench Carpenter',
   'Camera Operator',
   'Captain',
   'Cardiovascular Technologist',
   'Technician',
   'Career/Technical Education Teacher',
   'Career/Technical Education Teacher',
   'Cargo and Freight Agent',
   'Carpenter',
   'Carpet Installer',
   'Cartographer'];
const cities = ['Abilene',
   'Akron',
   'Albany',
   'Albuquerque',
   'Alexandria',
   'Allentown',
   'Amarillo',
   'Anaheim',
   'Anchorage',
   'Ann Arbor',
   'Antioch',
   'Apple Valley',
   'Appleton',
   'Arlington',
   'Arvada',
   'Asheville',
   'Athens',
   'Atlanta',
   'Atlantic City',
   'Augusta',
   'Aurora',
   'Austin',
   'Bakersfield',
   'Baltimore',
   'Barnstable',
   'Baton Rouge',
   'Beaumont',
   'Bel Air',
   'Bellevue',
   'Berkeley',
   'Bethlehem',
   'Billings',
   'Birmingham',
   'Bloomington',
   'Boise',
   'Boise City',
   'Bonita Springs',
   'Boston',
   'Boulder',
   'Bradenton',
   'Bremerton',
   'Bridgeport',
   'Brighton',
   'Brownsville',
   'Bryan',
   'Buffalo',
   'Burbank',
   'Burlington',
   'Cambridge',
   'Canton',
   'Cape Coral',
   'Carrollton',
   'Cary',
   'Cathedral City',
   'Cedar Rapids',
   'Champaign',
   'Chandler',
   'Charleston',
   'Charlotte',
   'Chattanooga',
   'Chesapeake',
   'Chicago',
   'Chula Vista',
   'Cincinnati',
   'Clarke County',
   'Clarksville',
   'Clearwater',
   'Cleveland',
   'College Station',
   'Colorado Springs',
   'Columbia',
   'Columbus',
   'Concord',
   'Coral Springs',
   'Corona',
   'Corpus Christi',
   'Costa Mesa',
   'Dallas',
   'Daly City',
   'Danbury',
   'Davenport',
   'Davidson County',
   'Dayton',
   'Daytona Beach',
   'Deltona',
   'Denton',
   'Denver',
   'Des Moines',
   'Detroit',
   'Downey',
   'Duluth',
   'Durham',
   'El Monte',
   'El Paso',
   'Elizabeth',
   'Elk Grove',
   'Elkhart',
   'Erie',
   'Escondido',
   'Eugene',
   'Evansville',
   'Fairfield',
   'Fargo',
   'Fayetteville',
   'Fitchburg',
   'Flint',
   'Fontana',
   'Fort Collins',
   'Fort Lauderdale',
   'Fort Smith',
   'Fort Walton Beach',
   'Fort Wayne',
   'Fort Worth',
   'Frederick',
   'Fremont',
   'Fresno',
   'Fullerton',
   'Gainesville',
   'Garden Grove',
   'Garland',
   'Gastonia',
   'Gilbert'];

const countries = ['Albania',
   'Algeria',
   'Andorra',
   'Angola',
   'Antigua & Deps',
   'Argentina',
   'Armenia',
   'Australia',
   'Austria',
   'Azerbaijan',
   'Bahamas',
   'Bahrain',
   'Bangladesh',
   'Barbados',
   'Belarus',
   'Belgium',
   'Belize',
   'Benin',
   'Bhutan',
   'Bolivia',
   'Bosnia Herzegovina',
   'Botswana',
   'Brazil',
   'Brunei',
   'Bulgaria',
   'Burkina',
   'Burundi',
   'Cambodia',
   'Cameroon',
   'Canada',
   'Cape Verde',
   'Central African Rep',
   'Chad',
   'Chile',
   'China',
   'Colombia',
   'Comoros',
   'Congo',
   'Congo {Democratic Rep}',
   'Costa Rica',
   'Croatia',
   'Cuba',
   'Cyprus',
   'Czech Republic',
   'Denmark',
   'Djibouti',
   'Dominica',
   'Dominican Republic',
   'East Timor',
   'Ecuador',
   'Egypt',
   'El Salvador',
   'Equatorial Guinea',
   'Eritrea',
   'Estonia',
   'Ethiopia',
   'Fiji',
   'Finland',
   'France',
   'Gabon',
   'Gambia',
   'Georgia',
   'Germany',
   'Ghana',
   'Greece',
   'Grenada',
   'Guatemala',
   'Guinea',
   'Guinea-Bissau',
   'Guyana',
   'Haiti',
   'Honduras',
   'Hungary',
   'Iceland',
   'India',
   'Indonesia',
   'Iran',
   'Iraq',
   'Ireland {Republic}',
   'Israel',
   'Italy',
   'Ivory Coast',
   'Jamaica',
   'Japan',
   'Jordan',
   'Kazakhstan',
   'Kenya',
   'Kiribati',
   'Korea North',
   'Korea South',
   'Kosovo',
   'Kuwait',
   'Kyrgyzstan',
   'Laos',
   'Latvia',
   'Lebanon',
   'Lesotho',
   'Liberia',
   'Libya',
   'Liechtenstein',
   'Lithuania',
   'Luxembourg',
   'Macedonia',
   'Madagascar',
   'Malawi',
   'Malaysia',
   'Maldives',
   'Mali',
   'Malta',
   'Marshall Islands',
   'Mauritania',
   'Mauritius',
   'Mexico',
   'Micronesia',
   'Moldova',
   'Monaco',
   'Mongolia',
   'Montenegro',
   'Morocco',
   'Mozambique',
   'Myanmar, {Burma}',
   'Namibia'];
for (let i = 0; i < 100; i++) {
   const paramsArr = [];

   // Contact_Owner
   const admin = admins[randomInt(admins.length)];
   paramsArr.push(admin);

   const name = namesArray[randomInt(namesArray.length)];
   // First_Name
   paramsArr.push(name.split(' ')[0]);
   // Last_Name
   paramsArr.push(name.split(' ')[1]);

   // Title
   paramsArr.push(titles[randomInt(titles.length)]);

   // Date_Of_Birth
   paramsArr.push(randomDate(new Date(1966, 0, 1), new Date(2002, 0, 1)));

   // Phone
   paramsArr.push(phoneVendor[randomInt(phoneVendor.length)] + '-' + randomIntInRange(1000000, 9999999));

   // Mobile
   paramsArr.push(moblieVendor[randomInt(moblieVendor.length)] + '-' + randomIntInRange(1000000, 9999999));

   // Email
   paramsArr.push(name.split(' ').join('') + randomInt(99) + '@' + emailVendors[randomInt(emailVendors.length)]);

   // Skype_ID
   paramsArr.push(randomIntInRange(100000, 99999999));

   // Street
   paramsArr.push(streets[randomInt(streets.length)]);

   // City
   paramsArr.push(cities[randomInt(cities.length)]);

   // Country
   paramsArr.push(countries[randomInt(countries.length)]);


   insert(paramsArr);
}



function insert(valuesArray) {
   connection.query(`INSERT INTO contact (Contact_Owner, First_Name, Last_Name, Title, Date_Of_Birth, Phone, Mobile, Email, Skype_ID, Street, City, Country) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`, valuesArray);
}

function randomDate(start, end) {
   return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}


function randomInt(max) {
   return Math.floor(Math.random() * max);
}

function randomIntInRange(min, max) {
   return min + Math.floor(Math.random() * (max - min));
}

